### ISSUE TITLE
如果Loading Failed layout中有点击按钮重新加载的需求，，

### ISSUE THREAD

**Issue by ghost** [LianjiaTech/ProgressLayout#2]
如果Loading Failed layout中有点击按钮重新加载的需求，那么如何改进呢。谢谢。

**Comment by SmartDengg** [comment]
如果这种情况的话，就需要在按钮的点击回调中手动调用`.showLoading()`，`.showContent()`等api。其实`.showFailed()`是个重载函数，可以不必传入后面的`retryListener`。

**Comment by ghost** [comment]
好,希望项目能有继续改进的地方。

**Comment by SmartDengg** [comment]
我的能否能都帮你解决问题，如果能的话，我就把这个issue关闭了。

**Comment by ghost** [comment]
OK,马上我会按照你的思路来完成这次项目的需求，如果有问题，我会持续咨询。

**Comment by SmartDengg** [comment]
OK，如果有需要帮助，可以再次打开这个issue，或者新开一个issue。
